import type { Metadata } from "next";
import "./globals.css";
import { Menu } from "@/components/menu";
import MobileTopbar from "@/components/mobiletopbar";


export const metadata: Metadata = {
  title: "DAWN AI",
  description: "Generated by DAWN AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='bg_gradient max-sm:p-[16px] max-lg:p-[12px]  md:mb-[70px]  max-container md:flex md:gap-[50px] lg:gap-[70px] xl:gap-[100px]'>
            <MobileTopbar/>
            <Menu />
            {children}
        
      </body>
    </html>
  );
}
